config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :replenishers
  resources :purchase_orders
  get 'sale_orders/report', to: 'sale_orders#report'
  resources :sale_orders
  resources :purchase_items
  resources :sale_items
  get "/results/:static", to: "results#show", as: 'result'
  root 'products#index'
  get 'products/list', to: 'products#list', as: 'list_items'
  resources :products, :categories, :suppliers
  resources :sale_orders do
    post :sale_item_fields, on: :collection
    post :sale_results, on: :collection
  end
  resources :purchase_orders do
    post :purchase_item_fields, on: :collection
    post :purchase_results, on: :collection
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/replenisher.rb
class Replenisher < ApplicationRecord
  has_many :purchase_orders
end

app/controllers/replenishers_controller.rb
class ReplenishersController < ApplicationController
  before_action :set_replenisher, only: [:show, :edit, :update, :destroy]
  def index
    @replenisher = Replenisher.all
  end

 def Show
 end

 def edit
 end

 def update
   respond_to do |format|
     if @replenisher.update(replenisher_params)
       format.html { redirect_to replenishers_path, notice: 'replenisher was successfully updated.' }
     else
       format.html { render :edit }
     end
   end
 end

 def new
  @replenisher = Replenisher.new
end

 def create
   @replenisher = Replenisher.new(replenisher_params)
   respond_to do |format|
     if @replenisher.save
       format.html { redirect_to replenishers_path, notice: 'The new replenisher is now live.' }
     else
       format.html { render :new }
     end
   end
 end

 def destroy
   #Destroy/delete the record
   @replenisher.destroy
   #Redirect
   respond_to do |format|
     format.html { redirect_to replenishers_path, notice: 'Category was successfully destroyed.' }
   end
 end

 private
 # Use callbacks to share common setup or constraints between actions.
 def set_replenisher
   @replenisher = Replenisher.find(params[:id])
 end

 # Never trust parameters from the scary internet, only allow the white list through.
 def replenisher_params
   params.require(:replenisher).permit(:fname, :lname, :email, :phone, :dni)
 end
end

app/helpers/replenishers_helper.rb
module ReplenishersHelper
end

app/views/replenishers/_form.html.erb
<%= form_for @replenisher do |form| %>
  <div class="form-group">
    <%= form.label :fname %>
    <%= form.text_field :fname, id: :replenisher_fname, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :lname %>
    <%= form.text_field :lname, id: :replenisher_lname, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, id: :replenisher_email, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :replenisher_phone, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :dni %>
    <%= form.text_field :dni, id: :replenisher_dni, class: "form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit :class=>"btn btn-primary"%>
  </div>
<% end %>

app/views/replenishers/edit.html.erb
<p id="notice"><%= notice %></p>
<h1><%=t('Edit replenisher')%></h1>

<%= render 'form', replenisher: @replenisher %>

app/views/replenishers/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-4 text-left">
    <h1><%=t('Replenishers')%></h1>
  </div>

  <div class="col-md-4 offset-md-4 text-right">
    <%= link_to '<i class="fa fa-plus fa-3x"></i>'.html_safe, new_replenisher_path %>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col"><%=t('first_name')%></th>
      <th scope="col"><%=t('last_name')%></th>
      <th scope="col"><%=t('Email')%></th>
      <th scope="col"><%=t('Phone')%></th>
      <th scope="col"><%=t('DNI')%></th>
      <th colspan="3" scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @replenisher.each do |replenisher_items| %>
      <tr>
        <td><%= replenisher_items.fname %></td>
        <td><%= replenisher_items.lname %></td>
        <td><%= replenisher_items.email %></td>
        <td><%= replenisher_items.phone %></td>
        <td><%= replenisher_items.dni %></td>
        <td><%= link_to t('Show'), replenisher_items, class: "btn btn-outline-dark btn-sm" %></td>
        <td><%= link_to t('Edit'), edit_replenisher_path(replenisher_items), class: "btn btn-outline-dark btn-sm" %></td>
        <td><%= link_to t('Destroy'), replenisher_path(replenisher_items), method: :delete, data: { confirm: t('Are you sure?') }, class: "btn btn-outline-dark btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/replenishers/new.html.erb
<h1><%=t('Create a new replenisher')%></h1>

<%= render 'form', replenisher: @replenisher %>

app/views/replenishers/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @replenisher.fname%> <%=@replenisher.lname  %></h1>

<ul>
  <li><span><%=t('Email')%>: </span><%= @replenisher.email %></li>

  <li><span><%=t('Phone')%>: </span><%= @replenisher.phone %></li>

  <li><span><%=t('DNI')%>: </span><%= @replenisher.dni %></li>

</ul>

<p><%= link_to t('Return Home'), replenishers_path %></p>