config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :replenishers
  resources :purchase_orders
  get 'sale_orders/report', to: 'sale_orders#report'
  resources :sale_orders
  resources :purchase_items
  resources :sale_items
  get "/results/:static", to: "results#show", as: 'result'
  root 'products#index'
  get 'products/list', to: 'products#list', as: 'list_items'
  resources :products, :categories, :suppliers
  resources :sale_orders do
    post :sale_item_fields, on: :collection
    post :sale_results, on: :collection
  end
  resources :purchase_orders do
    post :purchase_item_fields, on: :collection
    post :purchase_results, on: :collection
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :sale_orders
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  def index
    @customer = Customer.all
  end

 def Show
 end

 def edit
 end

 def update
   respond_to do |format|
     if @customer.update(customer_params)
       format.html { redirect_to customers_path, notice: 'customer was successfully updated.' }
     else
       format.html { render :edit }
     end
   end
 end

 def new
  @customer = Customer.new
end

 def create
   @customer = Customer.new(customer_params)
   respond_to do |format|
     if @customer.save
       format.html { redirect_to customers_path, notice: 'The new customer is now live.' }
     else
       format.html { render :new }
     end
   end
 end

 def destroy
   #Destroy/delete the record
   @customer.destroy
   #Redirect
   respond_to do |format|
     format.html { redirect_to customers_path, notice: 'Category was successfully destroyed.' }
   end
 end

 private
 # Use callbacks to share common setup or constraints between actions.
 def set_customer
   @customer = Customer.find(params[:id])
 end

 # Never trust parameters from the scary internet, only allow the white list through.
 def customer_params
   params.require(:customer).permit(:fname, :lname, :email, :phone, :dni)
 end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer do |form| %>
  <div class="form-group">
    <%= form.label :fname %>
    <%= form.text_field :fname, id: :customer_fname, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :lname %>
    <%= form.text_field :lname, id: :customer_lname, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, id: :customer_email, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :customer_phone, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :dni %>
    <%= form.text_field :dni, id: :customer_dni, class: "form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit :class=>"btn btn-primary"%>
  </div>
<% end %>

app/views/customers/edit.html.erb
<p id="notice"><%= notice %></p>
<h1><%=t('Edit customer')%></h1>

<%= render 'form', customer: @customer %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-4 text-left">
    <h1><%=t('Customers')%></h1>
  </div>

  <div class="col-md-4 offset-md-4 text-right">
    <%= link_to '<i class="fa fa-plus fa-3x"></i>'.html_safe, new_customer_path %>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col"><%=t('first_name')%></th>
      <th scope="col"><%=t('last_name')%></th>
      <th scope="col"><%=t('Email')%></th>
      <th scope="col"><%=t('Phone')%></th>
      <th scope="col"><%=t('DNI')%></th>
      <th colspan="3" scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer.each do |customer_items| %>
      <tr>
        <td><%= customer_items.fname %></td>
        <td><%= customer_items.lname %></td>
        <td><%= customer_items.email %></td>
        <td><%= customer_items.phone %></td>
        <td><%= customer_items.dni %></td>
        <td><%= link_to t('Show'), customer_items, class: "btn btn-outline-dark btn-sm" %></td>
        <td><%= link_to t('Edit'), edit_customer_path(customer_items), class: "btn btn-outline-dark btn-sm" %></td>
        <td><%= link_to t('Destroy'), customer_path(customer_items), method: :delete, data: { confirm: t('Are you sure?')}, class: "btn btn-outline-dark btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/new.html.erb
<h1><%=t('Create a new customer')%></h1>

<%= render 'form', customer: @customer %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @customer.fname%> <%=@customer.lname  %></h1>

<ul>
  <li><span><%=t('Email')%>: </span><%= @customer.email %></li>

  <li><span><%=t('Phone')%>: </span><%= @customer.phone %></li>

  <li><span><%=t('DNI')%>: </span><%= @customer.dni %></li>

</ul>

<p><%= link_to t('Return Home'), customers_path %></p>