config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :replenishers
  resources :purchase_orders
  get 'sale_orders/report', to: 'sale_orders#report'
  resources :sale_orders
  resources :purchase_items
  resources :sale_items
  get "/results/:static", to: "results#show", as: 'result'
  root 'products#index'
  get 'products/list', to: 'products#list', as: 'list_items'
  resources :products, :categories, :suppliers
  resources :sale_orders do
    post :sale_item_fields, on: :collection
    post :sale_results, on: :collection
  end
  resources :purchase_orders do
    post :purchase_item_fields, on: :collection
    post :purchase_results, on: :collection
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :supplier
  has_many :purchase_items
  has_many :purchase_orders, :through => :purchase_items
  has_many :sale_items
  has_many :sale_orders, :through => :sale_items
  before_save :calculate_level
  #Validations
  validates :stock, numericality: { greater_than_or_equal_to: 0 }

  filterrific(
    default_filter_params: { sorted_by: 'name_desc' },
    available_filters: [
        :sorted_by,
        :search_query,
        :with_category_id,
        :with_level
      ]
    )

  scope :search_query, lambda { |query|
    return nil  if query.blank?
    terms = query.downcase.split(/\s+/)
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    num_or_conds = 2
    where(
      terms.map { |term|
        "(LOWER(products.name) LIKE ? OR LOWER(products.brand) LIKE ?)"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conds }.flatten
    )
  }

  scope :with_category_id, lambda { |category_ids|
    where(category_id: [*category_ids])
  }

  scope :with_level, lambda { |levels|
    where(level: [*levels])
  }

  scope :sorted_by, lambda { |sort_options|
  direction = (sort_options =~ /desc$/) ? 'desc' : 'asc'

    case sort_options.to_s
    when /^name_/
      order("products.name #{ direction }")

    else
      raise(ArgumentError, "Invalid sort option")
    end
  }

  def self.options_for_sorted_by
    [
      ['Name (AZ)', 'name_asc'],
      ['Name (ZA)', 'name_desc']
     ]
  end

  def calculate_level
    if self.stock <= self.ss
      self.level = 'Reponer'
    elsif self.stock <= 2*self.ss
      self.level = 'Bajo'
    elsif self.stock <= 3*self.ss
      self.level = 'Medio'
    else
      self.level = 'Alto'
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :calculate_level, only: [:index]

  def index
    @filterrific = initialize_filterrific(
      Product,
      params[:filterrific],
      select_options: {
        sorted_by: Product.options_for_sorted_by,
        with_category_id: Category.options_for_select,
        with_level: Product.distinct.pluck(:level)
      }
    ) or return
    @products = @filterrific.find.paginate(page: params[:page], per_page: 15)

    respond_to do |format|
      format.html
      format.js
    end
    rescue ActiveRecord::RecordNotFound => e
      # There is an issue with the persisted param_set. Reset it.
      puts "Had to reset filterrific params: #{ e.message }"
      redirect_to(reset_filterrific_url(format: :html)) and return
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: t('Your product item is now live') }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    @list_items = Product.where(level: "Reponer")
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: t('Product was successfully updated') }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def list
    @list_items = Product.where(level: "Reponer")
    @suppliers = Supplier.distinct
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "list",
        template: "products/list.html.erb",
        encoding: "UTF-8",
        page_size: "A4",
        disable_internal_links: true
      end
    end
  end

  def destroy
    #Destroy/delete the record
    @product.destroy
    #Redirect
    respond_to do |format|
      format.html { redirect_to products_path, notice: t('Product was successfully destroyed') }
    end
  end

  def calculate_level
    @product_items = Product.all
    @product_items.each do |product|
      if product.stock <= product.ss
        product.level = 'Reponer'
        product.save
      elsif product.stock <= 2*product.ss
        product.level = 'Bajo'
        product.save
      elsif product.stock <= 3*product.ss
        product.level = 'Medio'
        product.save
      else
        product.level = 'Alto'
        product.save
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :upc, :brand, :unit,:price ,:stock, :ss, :deliver_time, :order_size, :supplier_id, :category_id ,:commentary)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  #Change row color helper
  def row_class(level)
    if level === "Alto"
      ''
    elsif level === "Medio"
      ''
    elsif level === "Bajo"
      'table-warning'
    else level === "Reponer"
      'table-danger'
    end
  end
end

app/views/products/_draft.html.erb
<div id="filterrific_results">
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th scope="col"><%=t('Name')%></th>
        <th scope="col"><%=t('Brand')%></th>
        <th scope="col"><%=t('Unit')%></th>
        <th scope="col"><%=t('Price')%></th>
        <th scope="col"><%=t('Stock')%></th>
        <th scope="col"><%=t('SS')%></th>
        <th scope="col"><%=t('Order_size')%></th>
        <th scope="col"><%=t('Supplier')%></th>
        <th scope="col"><%=t('Phone')%></th>
        <th scope="col"><%=t('Level')%></th>
        <th scope="col"><%=t('Category')%></th>
        <th colspan="3"  scope="col"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product_items|%>
      <tr class="<%= row_class(product_items.level) %>">
        <td><%= product_items.name %></td>
        <td><%= product_items.brand %></td>
        <td><%= product_items.unit %></td>
        <td><%= product_items.price %></td>
        <td><%= product_items.stock %></td>
        <td><%= product_items.ss %></td>
        <td><%= product_items.order_size %></td>
        <td><%= product_items.supplier.name %></td>
        <td><%= product_items.supplier.phone %></td>
        <td><%= product_items.level %></td>
        <td><%= product_items.category.name %></td>
        <td><%= link_to t('Show'), product_items, class: "btn btn-outline-dark btn-sm" %></td>
        <td><%= link_to t('Edit'), edit_product_path(product_items), class: "btn btn-outline-dark btn-sm" %></td>
        <td><%= link_to "", product_path(product_items), method: :delete, data: { confirm: t('Are you sure?') }, class: "fa fa-close" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate products %>

app/views/products/_form.html.erb
<%= form_with(model: @product, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :upc %>
    <%= form.text_field :upc, id: :product_upc, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :product_brand, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :unit %>
    <%= form.text_field :unit, id: :product_unit, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :stock %>
    <%= form.text_field :stock, id: :product_stock, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :ss %>
    <%= form.text_field :ss, id: :product_ss, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :deliver_time %>
    <%= form.text_field :deliver_time, id: :product_deliver_time, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :order_size %>
    <%= form.text_field :order_size, id: :product_order_size, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :supplier %>
    <%= form.collection_select :supplier_id, Supplier.all, :id, :name, {prompt: true}, {:class=>"form-control"}  %>
  </div>

  <div class="form-group">
    <%= form.label :category %>
    <%= form.collection_select :category_id, Category.all, :id, :name, {prompt: true}, {:class=>"form-control"}  %>
  </div>

  <div class="form-group">
    <%= form.label :commentary %>
    <%= form.text_area :commentary, id: :portfolio_commentary, class: "form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit :class=>"btn btn-primary"%>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1><%=t('Edit this product')%></h1>

<%= render 'form', product: @product %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-md-4 text-left">
      <h1><%= t('Products') %></h1>
    </div>

    <div class="col-md-4 offset-md-4 text-right">
      <%= link_to '<i class="fa fa-plus fa-3x"></i>'.html_safe, new_product_path %>
    </div>
  </div>

<div>
<p><%= link_to list_items_path(@list_items, :format => :pdf) do%>
<button type="button" class="btn btn-outline-dark btn-sm" data-toggle="tooltip" data-placement="top" title="Tooltip on top"><%=t('Generate list')%></button>
<%end%></p>
</div>

<%= form_for_filterrific @filterrific do |f| %>
<div class="form-row">
  <div class="form-group col-md-6">
    <label for="inputProduct"><%=t('Search')%></label>
    <%= f.text_field(
      :search_query,
      class: 'filterrific-periodically-observed form-control',
      id: 'inputProduct'
    ) %>
  </div>
  <div class="form-group col-md-4">
    <label for="selectCategory"><%=t('Category')%></label>
    <%= f.select(
      :with_category_id,
      @filterrific.select_options[:with_category_id],
      { include_blank: t('Any') },
      class: 'form-control',
      id: 'selectCategory'
    ) %>
  </div>
  <div class="form-group col-md-2">
    <label for="selectLevel"><%=t('Level')%></label>
    <%= f.select(:with_level, @filterrific.select_options[:with_level],
    { include_blank: t('Any') },
    class: 'form-control',
    id: 'selectLevels'
    ) %>
  </div>
  <%= render_filterrific_spinner %>
</div>
<%end%>


<%= render(
  partial: 'products/draft',
  locals: { products: @products }
) %>

</div>

app/views/products/index.js.erb
<% js = escape_javascript(
  render(partial: 'products/draft', locals: { products: @products })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/products/list.html.erb
<div class='container'>
  <%= wicked_pdf_stylesheet_link_tag "application" -%>
  <% @suppliers.each do |supplier|%>
    <div class="b">
        <h4><%= supplier.name %></h4>
        <p><span><%= t('Manager')%>: </span><%= supplier.manager %></p>
        <p><span><%= t('Phone')%>: </span><%= supplier.phone %></p>
        <p><span><%= t('Address')%>: </span><%= supplier.address %></p>
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col"><%=t('Name')%></th>
            <th scope="col"><%=t('Brand')%></th>
            <th scope="col"><%=t('Deliver_time')%></th>
            <th scope="col"><%=t('Order_size')%></th>
            <th scope="col"><%=t('Unit')%></th>
            <th scope="col"><%=t('Category')%></th>
          </tr>
        </thead>

        <tbody>
          <% @list_items.each do |list_item|%>
            <% if list_item.supplier == supplier %>
          <tr>
            <td class='pdftable'><%= list_item.name %></td>
            <td class='pdftable'><%= list_item.brand %></td>
            <td class='pdftable'><%= list_item.deliver_time %></td>
            <td class='pdftable'><%= list_item.order_size %></td>
            <td class='pdftable'><%= list_item.unit %></td>
            <td class='pdftable'><%= list_item.category.name %></td>
          </tr>
            <%end%>
          <% end %>
        </tbody>
      </table>
  </div>
<!--  <hr noshade>-->
  <%end%>
</div>

app/views/products/new.html.erb
<p id="notice"><%= notice %></p>
<h1><%=t('Create a new Product')%></h1>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @product.name %></h1>

<ul>
  <li><span><%=t('Stock')%>: </span><%= @product.stock %></li>

  <li><span><%=t('Category')%>: </span><%= @product.category.name %></li>

  <li><span><%=t('Category')%>: </span><%= @product.price %></li>

  <li><span><%=t('SS')%>: </span><%= @product.ss %></li>

  <li><span><%=t('Level')%>: </span><%= @product.level %></li>

  <li><span><%=t('Supplier')%>: </span><%= @product.supplier.name %></li>

  <li><span><%=t('Delivery_time')%>: </span><%= @product.deliver_time %></li>

  <li><span><%=t('Order_size')%>: </span><%= @product.order_size %></li>

  <li><span><%=t('Address')%>: </span><%= @product.supplier.address %></li>

  <li><span><%=t('Phone')%>: </span><%= @product.supplier.phone %></li>

  <li><span><%=t('Comment')%>: </span><%= @product.commentary %></li>
</ul>

<p><%= link_to t('Return Home'), products_path %></p>