config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :replenishers
  resources :purchase_orders
  get 'sale_orders/report', to: 'sale_orders#report'
  resources :sale_orders
  resources :purchase_items
  resources :sale_items
  get "/results/:static", to: "results#show", as: 'result'
  root 'products#index'
  get 'products/list', to: 'products#list', as: 'list_items'
  resources :products, :categories, :suppliers
  resources :sale_orders do
    post :sale_item_fields, on: :collection
    post :sale_results, on: :collection
  end
  resources :purchase_orders do
    post :purchase_item_fields, on: :collection
    post :purchase_results, on: :collection
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  def self.options_for_select
    order('LOWER(name)').map { |e| [e.name, e.id] }
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :sale_orders
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :supplier
  has_many :purchase_items
  has_many :purchase_orders, :through => :purchase_items
  has_many :sale_items
  has_many :sale_orders, :through => :sale_items
  before_save :calculate_level
  #Validations
  validates :stock, numericality: { greater_than_or_equal_to: 0 }

  filterrific(
    default_filter_params: { sorted_by: 'name_desc' },
    available_filters: [
        :sorted_by,
        :search_query,
        :with_category_id,
        :with_level
      ]
    )

  scope :search_query, lambda { |query|
    return nil  if query.blank?
    terms = query.downcase.split(/\s+/)
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    num_or_conds = 2
    where(
      terms.map { |term|
        "(LOWER(products.name) LIKE ? OR LOWER(products.brand) LIKE ?)"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conds }.flatten
    )
  }

  scope :with_category_id, lambda { |category_ids|
    where(category_id: [*category_ids])
  }

  scope :with_level, lambda { |levels|
    where(level: [*levels])
  }

  scope :sorted_by, lambda { |sort_options|
  direction = (sort_options =~ /desc$/) ? 'desc' : 'asc'

    case sort_options.to_s
    when /^name_/
      order("products.name #{ direction }")

    else
      raise(ArgumentError, "Invalid sort option")
    end
  }

  def self.options_for_sorted_by
    [
      ['Name (AZ)', 'name_asc'],
      ['Name (ZA)', 'name_desc']
     ]
  end

  def calculate_level
    if self.stock <= self.ss
      self.level = 'Reponer'
    elsif self.stock <= 2*self.ss
      self.level = 'Bajo'
    elsif self.stock <= 3*self.ss
      self.level = 'Medio'
    else
      self.level = 'Alto'
    end
  end

end

app/models/purchase_item.rb
class PurchaseItem < ApplicationRecord
  belongs_to :product
  belongs_to :purchase_order, inverse_of: :purchase_items
  after_destroy :decrement_stock
  after_create :increment_stock
  def decrement_stock
    if self.product.stock >= self.quantity
      self.product.update_attribute("stock", (product.stock - self.quantity))
    else
      errors.add(:product, message: "cannot be nil")
    end
  end
  def increment_stock
    self.product.update_attribute("stock", (product.stock + self.quantity))
  end
end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
  has_many :purchase_items, inverse_of: :purchase_order, dependent: :destroy
  has_many :products, :through => :purchase_items
  belongs_to :replenisher
  #enable nested attributes
  accepts_nested_attributes_for :purchase_items, allow_destroy: true, :reject_if => :all_blank

end

app/models/replenisher.rb
class Replenisher < ApplicationRecord
  has_many :purchase_orders
end

app/models/sale_item.rb
class SaleItem < ApplicationRecord
  belongs_to :product
  belongs_to :sale_order, inverse_of: :sale_items
  after_create :decrement_stock
  after_destroy :increment_stock
  def decrement_stock
    if self.product.stock >= self.quantity
      self.product.update_attribute("stock", (product.stock - self.quantity))
    else
      errors.add(:product, message: "Cannot be nil")
    end
  end
  def increment_stock
    self.product.update_attribute("stock", (product.stock + self.quantity))
  end
end

app/models/sale_order.rb
class SaleOrder < ApplicationRecord
  has_many :sale_items, inverse_of: :sale_order, dependent: :destroy
  has_many :products, :through => :sale_items
  belongs_to :customer
  #enable nested attributes
  accepts_nested_attributes_for :sale_items, allow_destroy: true, :reject_if => :all_blank
  #Validations
  validates_associated :products
  validate do |sale_order|
    sale_order.sale_items.each do |sale_item|
      sale_item.errors.full_messages.each do |msg|
        # you can customize the error message here:
        errors.add("Sale items Error: #{msg}")
      end
    end
  end

  def self.to_csv
    CSV.generate(headers: true) do |csv|
    csv << column_names
    all.each do |sale_order|
      csv << sale_order.attributes.merge(sale_order.customer.attributes).values_at(*column_names)
    end
  end
end

end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  has_many :products
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def show
    @sale_items = SaleItem.paginate(:page => params[:page], :per_page => 15).order('created_at DESC')
    @total_sales = SaleItem.sum(:price)
    render "results/#{params[:static]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  #Change row color helper
  def row_class(level)
    if level === "Alto"
      ''
    elsif level === "Medio"
      ''
    elsif level === "Bajo"
      'table-warning'
    else level === "Reponer"
      'table-danger'
    end
  end
end

app/helpers/purchase_items_helper.rb
module PurchaseItemsHelper
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/helpers/replenishers_helper.rb
module ReplenishersHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/sale_items_helper.rb
module SaleItemsHelper
end

app/helpers/sale_orders_helper.rb
module SaleOrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InventorySys</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <% I18n.available_locales %>
  <%= favicon_link_tag asset_path('favicon.ico') %>
</head>

<body>
  <div class="wrapper">
    <!--Navbar content -->
    <nav id="sidebar" class="navbar-expand-lg navbar-light bg-light">
      <div class="sidebar-header">
          <h3><%=t('Inventory')%></h3>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <%= link_to result_path("dashboard"), { :class=>"nav-link" } do%>
            <i class="fa fa-dashboard" aria-hidden="true"></i>
          <%=t('Dashboard')%>
          <%end%>
        </li>
        <li class="list-group-item">
          <%= link_to sale_orders_path, { :class=>"nav-link" } do%>
            <i class="fa fa-share-square-o" aria-hidden="true"></i>
            <%=t('Sale_orders')%>
          <%end%>
        </li>
        <li class="list-group-item">
          <%= link_to purchase_orders_path, { :class=>"nav-link" } do%>
          <i class="fa fa-cart-plus" aria-hidden="true"></i>
          <%=t('Purchase_orders')%>
          <%end%>
        </li>
        <li class="list-group-item">
          <%= link_to products_path, { :class=>"nav-link" } do%>
          <i class="fa fa-product-hunt" aria-hidden="true"></i>
          <%=t('Products')%>
          <%end%>
        </li>
        <li class="list-group-item">
          <%= link_to categories_path, { :class=>"nav-link" } do%>
          <i class="fa fa-clone" aria-hidden="true"></i>
          <%=t('Categories')%>
          <%end%>
        </li>
        <li class="list-group-item">
          <%= link_to suppliers_path, { :class=>"nav-link" } do%>
          <i class="fa fa-truck" aria-hidden="true"></i>
          <%=t('Suppliers')%>
          <%end%>
        </li>
        <li class="list-group-item">
          <%= link_to customers_path, { :class=>"nav-link" } do%>
          <i class="fa fa-male" aria-hidden="true"></i>
          <%=t('Customers')%>
          <%end%>
        </li>
        <li class="list-group-item">
          <%= link_to replenishers_path, { :class=>"nav-link" } do%>
          <i class="fa fa-share-square-o" aria-hidden="true"></i>
          <%=t('Replenishers')%>
          <%end%>
        </li>
      </ul>
    </nav>

    <!--start content-->
    <div id="content" class="flex-fill">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
              <button type="button" id="sidebarCollapse" class="btn btn-info">
                  <span class="navbar-toggler-icon"></span>
              </button>
          </div>
      </nav>
      <%= yield %>
    </div>
  </div>
</body>
</html>